### ISSUE TITLE
Calling this "2.0" is going to get very confusing

### ISSUE THREAD

**Issue by madwort** [madwort/improv-analysis-2.0#1]
Currently on version "0.2" of "2.0"

**Comment by rconstanzo** [comment]
Maybe let's just build towards "1.0", with that being _actually_ "2.0", but we'll just treat the previous version as an alpha.

**Comment by madwort** [comment]
🤝

**Comment by madwort** [comment]
You know what, I think it would be useful to preserve the git history, I'm going to merge this into the previous repo as v2.
